import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src='https://kit.fontawesome.com/66eaecb2cd.js' />
      {/* <Script src='./node_modules/flowbite/dist/flowbite.min.js' /> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
